"use client";
import { FormEvent,useEffect,useMemo,useState } from "react";
type Ingredient={id:number;name:string;brand:string;calories:number;reference_amount:number;unit:string;source_type:string;source_name:string;source_url:string};
type Recipe={id:number;name:string;servings:number;notes:string;total_calories:number};type Item={id:number;recipe_id:number;amount:number;name:string;unit:string};type Log={id:number;recipe_name:string;servings_made:number;total_calories:number;cooked_at:string};
type Data={ingredients:Ingredient[];recipes:Recipe[];recipeItems:Item[];logs:Log[]};const empty:Data={ingredients:[],recipes:[],recipeItems:[],logs:[]};
export function FoodFatApp(){
 const [data,setData]=useState(empty),[view,setView]=useState("overview"),[dialog,setDialog]=useState<"ingredient"|"recipe"|"log"|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const [food,setFood]=useState({name:"",brand:"",calories:"",referenceAmount:"100",unit:"g",sourceType:"品牌營養標示",sourceName:"",sourceUrl:""});
 const [recipe,setRecipe]=useState({name:"",servings:"1",notes:""}),[items,setItems]=useState([{ingredientId:"",amount:""}]),[log,setLog]=useState({recipeId:"",servingsMade:"1"});
 const load=async()=>{const r=await fetch("/api/data");const j=await r.json();if(!r.ok)throw new Error(j.error);setData(j)};useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 const today=useMemo(()=>data.logs.filter(x=>new Date(x.cooked_at+"Z").toDateString()===new Date().toDateString()).reduce((s,x)=>s+Number(x.total_calories),0),[data.logs]);
 const save=async(payload:object)=>{setBusy(true);setError("");try{const r=await fetch("/api/data",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),j=await r.json();if(!r.ok)throw new Error(j.error);await load();setDialog(null)}catch(e){setError(e instanceof Error?e.message:"儲存失敗")}finally{setBusy(false)}};
 const open=(x:typeof dialog)=>{setError("");setDialog(x)};
 return <main><header className="topbar"><button className="brand" onClick={()=>setView("overview")}>Food<span>Fat</span></button><nav>{[["overview","今日總覽"],["ingredients","食材庫"],["recipes","我的食譜"]].map(x=><button key={x[0]} className={view===x[0]?"active":""} onClick={()=>setView(x[0])}>{x[1]}</button>)}</nav><span className="avatar">YU</span></header>
 {view==="overview"&&<><section className="hero"><div><p className="eyebrow">MY KITCHEN JOURNAL</p><h1>今天，想做點<br/><em>什麼好吃的？</em></h1><p className="intro">從營養標籤到餐桌，精準掌握每一份料理的熱量。</p></div><button className="primary" onClick={()=>open("log")} disabled={!data.recipes.length}>＋ 記錄本次烹飪</button></section><section className="dashboard-grid"><article className="calorie-card"><div><p className="eyebrow">今日烹飪總熱量</p><strong>{Math.round(today).toLocaleString()}</strong><span> kcal</span></div><div className="ring"><b>{data.logs.length}</b><small>歷史紀錄</small></div><p className="goal">此數字為今日記錄的整批料理熱量</p></article><article className="quick-card"><Heading label="QUICK START" title="從我的食譜開始"/><div className="recipe-row">{data.recipes.slice(0,3).map((r,i)=><button key={r.id} onClick={()=>{setLog({recipeId:String(r.id),servingsMade:String(r.servings)});open("log")}}><Icon name={r.name} i={i}/><b>{r.name}</b><small>{Math.round(r.total_calories/r.servings)} kcal / 份</small></button>)}{!data.recipes.length&&<p className="empty">先建立第一份食譜，下次烹飪就不用重新輸入。</p>}</div></article></section><section className="library"><Heading label="COOKING LOG" title="最近烹飪"/><div className="ingredient-list">{data.logs.map(x=><div key={x.id}><span className="dot green"/><b>{x.recipe_name}</b><small>{new Date(x.cooked_at+"Z").toLocaleString("zh-TW")} · {x.servings_made} 份</small><strong>{Math.round(x.total_calories)} <i>kcal</i></strong></div>)}{!data.logs.length&&<p className="empty">尚無烹飪紀錄。</p>}</div></section></>}
 {view==="ingredients"&&<Page title="我的食材庫" label="PANTRY" intro="保存包裝營養標示或公開資料來源，熱量換算更可信。" button="＋ 新增食材" action={()=>open("ingredient")}><div className="data-grid">{data.ingredients.map((x,i)=><article className="data-card" key={x.id}><Icon name={x.name} i={i}/><div><small>{x.brand||"一般食材"}</small><h3>{x.name}</h3></div><strong>{x.calories} <i>kcal / {x.reference_amount}{x.unit}</i></strong><p>{x.source_type} · {x.source_name||"未註明名稱"}</p>{x.source_url&&<a href={x.source_url} target="_blank" rel="noreferrer">查看資料來源 ↗</a>}</article>)}{!data.ingredients.length&&<Empty text="先新增一項營養標示資料吧。"/>}</div></Page>}
 {view==="recipes"&&<Page title="我的食譜" label="RECIPE BOOK" intro="食材與份量保存一次，之後每次烹飪直接套用。" button="＋ 建立食譜" action={()=>open("recipe")} disabled={!data.ingredients.length}>{!data.ingredients.length&&<p className="notice">建立食譜前，請先到食材庫新增食材。</p>}<div className="data-grid">{data.recipes.map((r,i)=><article className="data-card recipe-card" key={r.id}><Icon name={r.name} i={i}/><div><small>{r.servings} 份</small><h3>{r.name}</h3></div><strong>{Math.round(r.total_calories/r.servings)} <i>kcal / 份</i></strong><ul>{data.recipeItems.filter(x=>x.recipe_id===r.id).map(x=><li key={x.id}>{x.name} {x.amount}{x.unit}</li>)}</ul><button className="outline" onClick={()=>{setLog({recipeId:String(r.id),servingsMade:String(r.servings)});open("log")}}>記錄這次烹飪</button></article>)}{!data.recipes.length&&<Empty text="建立常做的料理，下次一鍵記錄。"/>}</div></Page>}
 {dialog&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setDialog(null)}}><div className="modal" role="dialog" aria-modal="true"><button className="close" onClick={()=>setDialog(null)}>×</button>
 {dialog==="ingredient"&&<form onSubmit={(e)=>{e.preventDefault();save({type:"ingredient",ingredient:{...food,calories:Number(food.calories),referenceAmount:Number(food.referenceAmount)}})}}><Heading label="NEW INGREDIENT" title="新增食材資料"/><div className="form-grid"><Field name="食材名稱"><input required value={food.name} onChange={e=>setFood({...food,name:e.target.value})}/></Field><Field name="品牌（選填）"><input value={food.brand} onChange={e=>setFood({...food,brand:e.target.value})}/></Field><Field name="熱量 kcal"><input required min="0" step=".1" type="number" value={food.calories} onChange={e=>setFood({...food,calories:e.target.value})}/></Field><Field name="標示基準量"><input required min=".1" step=".1" type="number" value={food.referenceAmount} onChange={e=>setFood({...food,referenceAmount:e.target.value})}/></Field><Field name="單位"><select value={food.unit} onChange={e=>setFood({...food,unit:e.target.value})}>{["g","ml","份","顆"].map(x=><option key={x}>{x}</option>)}</select></Field><Field name="資料類型"><select value={food.sourceType} onChange={e=>setFood({...food,sourceType:e.target.value})}>{["品牌營養標示","政府公開資料","其他公開數據"].map(x=><option key={x}>{x}</option>)}</select></Field><Field wide name="來源名稱"><input placeholder="例如：包裝背面營養標示" value={food.sourceName} onChange={e=>setFood({...food,sourceName:e.target.value})}/></Field><Field wide name="來源網址（選填）"><input type="url" value={food.sourceUrl} onChange={e=>setFood({...food,sourceUrl:e.target.value})}/></Field></div><End busy={busy} error={error}/></form>}
 {dialog==="recipe"&&<form onSubmit={(e)=>{e.preventDefault();save({type:"recipe",recipe:{...recipe,servings:Number(recipe.servings),items:items.map(x=>({ingredientId:Number(x.ingredientId),amount:Number(x.amount)}))}})}}><Heading label="NEW RECIPE" title="建立可重複使用的食譜"/><div className="form-grid"><Field name="食譜名稱"><input required value={recipe.name} onChange={e=>setRecipe({...recipe,name:e.target.value})}/></Field><Field name="完成份數"><input required min=".1" step=".1" type="number" value={recipe.servings} onChange={e=>setRecipe({...recipe,servings:e.target.value})}/></Field><Field wide name="做法備註"><textarea rows={3} value={recipe.notes} onChange={e=>setRecipe({...recipe,notes:e.target.value})}/></Field></div><h3>食材與用量</h3>{items.map((x,i)=><div className="item-row" key={i}><select required value={x.ingredientId} onChange={e=>setItems(items.map((a,n)=>n===i?{...a,ingredientId:e.target.value}:a))}><option value="">選擇食材</option>{data.ingredients.map(a=><option key={a.id} value={a.id}>{a.name}（{a.unit}）</option>)}</select><input required min=".1" step=".1" type="number" placeholder="用量" value={x.amount} onChange={e=>setItems(items.map((a,n)=>n===i?{...a,amount:e.target.value}:a))}/>{items.length>1&&<button type="button" onClick={()=>setItems(items.filter((_,n)=>n!==i))}>移除</button>}</div>)}<button className="add-row" type="button" onClick={()=>setItems([...items,{ingredientId:"",amount:""}])}>＋ 再加一項食材</button><End busy={busy} error={error}/></form>}
 {dialog==="log"&&<form onSubmit={(e)=>{e.preventDefault();save({type:"log",recipeId:Number(log.recipeId),servingsMade:Number(log.servingsMade)})}}><Heading label="COOKING LOG" title="記錄本次烹飪"/><div className="form-grid"><Field wide name="使用食譜"><select required value={log.recipeId} onChange={e=>setLog({...log,recipeId:e.target.value})}><option value="">選擇食譜</option>{data.recipes.map(x=><option key={x.id} value={x.id}>{x.name}（原食譜 {x.servings} 份）</option>)}</select></Field><Field wide name="本次製作份數"><input required min=".1" step=".1" type="number" value={log.servingsMade} onChange={e=>setLog({...log,servingsMade:e.target.value})}/></Field></div><End busy={busy} error={error}/></form>}</div></div>}
 </main>}
function foodEmoji(name:string){const n=name.toLowerCase();const choices:[string[],string][]=[[['蛋','egg'],'🍳'],[['奶','乳','milk','起司','cheese'],'🥛'],[['燕麥','麥片','oat','rice','飯','米'],'🥣'],[['雞','chicken'],'🍗'],[['豬','肉','beef','牛'],'🥩'],[['魚','鮭','fish','蝦','seafood'],'🐟'],[['番茄','tomato'],'🍅'],[['菜','沙拉','蔬','lettuce'],'🥗'],[['蘋果','apple'],'🍎'],[['香蕉','banana'],'🍌'],[['麵包','toast','bread'],'🍞'],[['湯','soup','粥'],'🍲'],[['咖啡','coffee'],'☕'],[['豆','tofu','豆腐'],'🫘'],[['菇','mushroom'],'🍄']];return choices.find(([words])=>words.some(word=>n.includes(word)))?.[1]??'🍽️'}
function Heading({label,title}:{label:string;title:string}){return <div className="card-heading"><div><p className="eyebrow">{label}</p><h2>{title}</h2></div></div>};function Icon({name,i}:{name:string;i:number}){return <span className={`food-icon ${["yellow","green","pink"][i%3]}`} role="img" aria-label={`${name}插圖`}>{foodEmoji(name)}</span>}
function Page({label,title,intro,button,action,disabled,children}:{label:string;title:string;intro:string;button:string;action:()=>void;disabled?:boolean;children:React.ReactNode}){return <section className="page-section"><div className="section-title"><div><p className="eyebrow">{label}</p><h1>{title}</h1><p>{intro}</p></div><button className="primary" disabled={disabled} onClick={action}>{button}</button></div>{children}</section>}
function Field({name,wide,children}:{name:string;wide?:boolean;children:React.ReactNode}){return <label className={wide?"wide":""}>{name}{children}</label>}function Empty({text}:{text:string}){return <div className="empty-card"><b>空空如也</b><p>{text}</p></div>}function End({busy,error}:{busy:boolean;error:string}){return <><p className="form-error">{error}</p><button className="primary submit" disabled={busy}>{busy?"儲存中…":"儲存"}</button></>}
